apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: platform-public-ingress-baseline
  namespace: platform
  labels:
    app.kubernetes.io/part-of: k8s-platform-template
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - {}
