apiVersion: v1
kind: Service
metadata:
  name: metrics-server
  namespace: platform
  labels:
    app: metrics-server
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 443
    targetPort: https
    protocol: TCP
  selector:
    app: metrics-server
