apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: platform
  labels:
    app: httpbin
spec:
  type: ClusterIP
  selector:
    app: httpbin
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
