expose:
  type: ingress
  tls:
    enabled: true
    certSource: secret
    secret:
      secretName: __HARBOR_TLS_SECRET__
  ingress:
    className: ""
    annotations: {}
    hosts:
      core: __HARBOR_HOST__

externalURL: __HARBOR_EXTERNAL_URL__
harborAdminPassword: __HARBOR_ADMIN_PASSWORD__
secretKey: __HARBOR_SECRET_KEY__

persistence:
  enabled: true
  resourcePolicy: keep
  persistentVolumeClaim:
    registry:
      storageClass: __PLATFORM_STORAGE_CLASS__
      accessMode: ReadWriteOnce
      size: 100Gi
    jobservice:
      jobLog:
        storageClass: __PLATFORM_STORAGE_CLASS__
        accessMode: ReadWriteOnce
        size: 10Gi
    database:
      storageClass: __PLATFORM_STORAGE_CLASS__
      accessMode: ReadWriteOnce
      size: 20Gi
    redis:
      storageClass: __PLATFORM_STORAGE_CLASS__
      accessMode: ReadWriteOnce
      size: 5Gi
    trivy:
      storageClass: __PLATFORM_STORAGE_CLASS__
      accessMode: ReadWriteOnce
      size: 20Gi

database:
  type: internal

redis:
  type: internal

trivy:
  enabled: true
