apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  
  nfs:
    server: __SHARED_STORAGE_NFS_SERVER__
    path: __SHARED_STORAGE_NFS_PATH__
